const light = {
  title: "light",

  colors: {
    primary: "#ff1a73",
    secundary: "#4aade5",
    secundaryLight: "#DAEEFA",
    tertiary: "#ffffff",
    tertiaryLight: "#ffffff",
    background: "#eea0ae",
    backgroundGradient: "#f3afbb",
    backgroundLight: "#f5ebf3",
    text: "#353535",
    formColor: "#5c8599",
    inputColor: "#5c8599",
    borderFormColor: "#d3e2e5",
    buttonBackground: "#3cdc8c",
    buttonBackgroundLight: "#D8F8E8",
    buttonHoverBackground: "#3EE08F",
    pink: "#ff1a73",
    pinkMedium: "#FF669D",
    pinkLight: "#FFD1E3",
    pinkDark: "#d6487b",
    green: "#37C77F",
    greenMedium: "#3BD689",
    greenDark: "#31B272",
    white: "#ffffff",
  },
  bp: {
    mobileS: `max-width: 330px`,
    mobileM: `max-width: 400px`,
    mobileL: `max-width: 480px`,
    tabletS: `max-width: 600px`,
    tabletL: `max-width: 768px`,
    desktopXS: `max-width: 900px`,
    desktopS: `max-width: 1080px`,
    desktopM: `max-width: 1200px`,
    desktopL: `max-width: 1400px`,
  },
};

export default light;
